### ISSUE TITLE
Continue with and display name

### ISSUE THREAD

**Issue by mihaidu** [mrahhal/MR.AspNetCore.Jobs#11]
I want to use this library. Is there any possibility to enqueue chained jobs? Also, can the job be named like with an attribute DisplayName?

**Comment by mrahhal** [comment]
By enqueuing chained jobs, do you to be able to enqueue a job that is scheduled to execute after another job finishes? If so, right now you can't describe this relation between jobs. But you can enqueue another job in the first job that is being executed, I guess.

Naming cron jobs? Or do you mean naming delayed jobs?

**Comment by mihaidu** [comment]
The flow will be , when the job With ID x finish will run the job with ID y and when this finish will run the Job with id Z. For what i understand its not possible. 

By naming i mean store in the database the query with the ID and a custom name that later can be viewed in a admin area. Its that possible ?

**Comment by mrahhal** [comment]
Yes the flow you mentioned isn't supported explicitly right now (as I said, you can emulate this behavior in some way).

Yeah there'll be names and other metadata once I get to work on an administration module. (I don't have nearly as much time as I'd have liked to work on this)

**Comment by mihaidu** [comment]
Any suggestion on how i can emulate this?

**Comment by mihaidu** [comment]
Some sample will be great

**Comment by mrahhal** [comment]
Suppose you have 2 jobs, "A" and "B". In job A, you can inject `IJobsManager`, and in its execution method at the end, you can simply:
```
// JobA's execution logic.
...

// And then enqueue an execution of JobB.
await _jobsManager.EnqueueAsync<JobB>(...);
```

This way, JobB will execute after JobA is finished. Let me know if this is still unclear.

Supporting this kind of thing is possible but I can't think of a good design right now.

**Comment by mihaidu** [comment]
i have jobs that need to run in parallel like this. Job A ( job a1. Download, Job A2 Process, Job A3 Upload, Job A4 clean) The idea is that i want to do all in parallel like a flow and not using any service bus queue for example .

**Comment by mihaidu** [comment]
but you solution looks right i will try it. Thanks

**Comment by mrahhal** [comment]
If you would elaborate more on this. Do you mean "in a process" instead of "in parallel". Are each of these jobs chained together in a single line?

Or are some of those unrelated to the others? I can't comprehend the flow here.
