### ISSUE TITLE
Migration to AspNetCor 2.1 fails with error: TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Infrastructure.Internal.SqlServerOptionsExtension' from assembly 'Microsoft.EntityFrameworkCore.SqlServer, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

### ISSUE THREAD

**Issue by ralfbalzer** [mrahhal/MR.AspNetCore.Jobs#13]
I am trying to upgrade to AspNetCore 2.1 but am getting the above error. 
This seems to be a reference in the following code: MR.AspNetCore.Jobs.SqlServer/SqlServerJobsOptionsExtension.cs .

Could you have a look and try to upgrade the package to be compatible with 2.1?

**Comment by mrahhal** [comment]
Will upgrade to 2.1 very soon.

**Comment by mrahhal** [comment]
`0.9.0`

**Comment by ralfbalzer** [comment]
I upgraded the package today and all my tests have passed.
Thank you for the quick response and for creating the package in the first place. It is very useful.

**Comment by mrahhal** [comment]
Thanks. Hopefully, sometime in the future I'll be able to get some free time and release a 6 months overdue 1.0 release :)
